### ISSUE TITLE
[BUG] Chunks stacking

### ISSUE THREAD

**Issue by DoubleMaul** [ConnorDY/OSRS-Environment-Exporter#104]
- [x] I am using the latest version of the exporter

## Bug description
when exporting in kourend (could be in other places) the chunks stack

![image](https://user-images.githubusercontent.com/110874865/185012244-aecfd0bd-11b7-4a19-857c-30f7b90cc516.png)

## Steps to reproduce

1. export the chunk 4922
2. import .gtlf in blender

## The current behavior

in kourend, could be other places, the chunks stack even if you only enter in one chunk into the exporter
![image](https://user-images.githubusercontent.com/110874865/185012631-be0b6a40-d699-48c3-9769-9dc53b29818b.png)

## The expected behavior
no stacking
![image](https://user-images.githubusercontent.com/110874865/185012857-6279fb42-43be-44e3-9f32-9613b750707f.png)

**Comment by ConnorDY** [comment]
This bug was found using the build from the following commit:
431ea41da33cda93184b88adca38bb00d135f23d

**Comment by ConnorDY** [comment]
**More Info:**

The render preview was also not working and seems to be related to the issue described above.

The following error message was repeating infinitely in the logs:
```
Exception in thread "AWT-EventQueue-0" java.lang.OutOfMemoryError: Out of stack space.
        at org.lwjgl.system.MemoryStack.nmalloc(MemoryStack.java:315)
        at org.lwjgl.system.MemoryStack.nUTF16(MemoryStack.java:848)
        at org.lwjgl.system.MemoryStack.nUTF16Safe(MemoryStack.java:866)
        at org.lwjgl.system.windows.User32.CreateWindowEx(User32.java:1241)
        at org.lwjgl.opengl.awt.PlatformWin32GLCanvas.createDummyWindow(PlatformWin32GLCanvas.java:135)
        at org.lwjgl.opengl.awt.PlatformWin32GLCanvas.create(PlatformWin32GLCanvas.java:154)
        at org.lwjgl.opengl.awt.AWTGLCanvas.beforeRender(AWTGLCanvas.java:60)
        at org.lwjgl.opengl.awt.AWTGLCanvas.render(AWTGLCanvas.java:101)
        at controllers.worldRenderer.helpers.Animator$RenderRunnable.run(Animator.kt:28)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
